------------------------------- MODULE Trace -------------------------------
(***************************************************************************)
(* Replays a recorded execution of the real cluster against the model.      *)
(*                                                                         *)
(* Replication.tla asks whether the design is correct. This asks the        *)
(* question that connects the design to the code: did the running system    *)
(* only ever do things the model permits? Every recorded observation must   *)
(* correspond to a legal step. If TLC cannot take one, it stops with no     *)
(* successor state and names the event - the implementation left the        *)
(* behaviour the specification describes.                                   *)
(*                                                                         *)
(* TraceData.tla is generated by TestTraceConformance in tests/sim and is   *)
(* not committed: the point is to check the implementation as it is now,    *)
(* not as it was when a fixture was recorded. Run `make spec-trace`.        *)
(***************************************************************************)
EXTENDS Replication, Sequences, TraceData

VARIABLE ti  \* index of the next trace event to explain

tvars == <<vars, ti>>

Ev == TraceEvents[ti]

(* A client write or delete began. The model mints the next version; it must
   be the one the recording saw, which is what ties the two version spaces
   together. Tombstone is the string "tombstone", the same token the
   recorder emits, so writes and deletes take the same branch. *)
StartStep ==
    /\ Ev.kind = "start"
    /\ StartWrite(Ev.val)
    /\ inflight'.ver = Ev.ver

(* A replica now holds a version it did not hold before.

   The recorder sees this through a store callback, which reveals *that* the
   replica advanced but not *which mechanism* advanced it: the original
   fan-out, a hinted handoff, and an anti-entropy repair are indistinguishable
   from there. So the step is satisfied by any of the three, provided it
   leaves the replica at the observed version.

   That is deliberately a weaker claim than naming the mechanism, and the
   honest one for what the harness can see: the check is that *some* legal
   step explains the observation, not that we know which one occurred. *)
DeliverStep ==
    /\ Ev.kind = "deliver"
    /\ \/ DeliverWrite(Ev.node)
       \/ DeliverHint(Ev.node)
       \/ \E a \in Nodes : AntiEntropy(a, Ev.node)
    /\ store'[Ev.node].ver = Ev.ver

DownStep ==
    /\ Ev.kind = "down"
    /\ Crash(Ev.node)

UpStep ==
    /\ Ev.kind = "up"
    /\ Recover(Ev.node)

GCStep ==
    /\ Ev.kind = "gc"
    /\ CollectTombstone
    /\ gcVer' = Ev.ver

ObservedStep ==
    /\ ti <= Len(TraceEvents)
    /\ \/ StartStep
       \/ DeliverStep
       \/ DownStep
       \/ UpStep
       \/ GCStep
    /\ ti' = ti + 1

(* Steps the recorder cannot see, allowed to happen between observed events
   without advancing the trace.

   There are exactly two, and both are unobservable for the same concrete
   reason: they change no replica's store, so no store callback fires.

     - FinishWrite closes a fan-out.
     - A leg of a fan-out aimed at a replica that has since become
       unreachable. It buffers a hint and leaves every store untouched. This
       one is easy to forget and its absence is not hypothetical: the first CI
       run of this check failed because a replica crashed mid-fan-out, leaving
       its leg outstanding forever, so `pending` never emptied and the next
       write could not start. Locally every replica had received the write
       before the crash and the gap never showed.

   Restraint here is what keeps the check meaningful - a model free to take
   arbitrary hidden steps could explain almost any observation - so the second
   case is deliberately narrow: only for a replica that is actually down, and
   only via DeliverWrite, which cannot alter a store in that state. *)
InternalStep ==
    \/ /\ FinishWrite
       /\ UNCHANGED ti
    \/ /\ \E n \in Nodes : n \notin up /\ DeliverWrite(n)
       /\ UNCHANGED ti

(* Once every event is explained the behaviour may stutter, so reaching the
   end of the trace is not itself reported as a stuck state. *)
Done ==
    /\ ti > Len(TraceEvents)
    /\ UNCHANGED tvars

TraceInit == Init /\ ti = 1

TraceNext == ObservedStep \/ InternalStep \/ Done

TraceSpec == TraceInit /\ [][TraceNext]_tvars

(***************************************************************************)
(* How conformance is decided.                                             *)
(*                                                                         *)
(* An observation can often be explained by more than one action - a        *)
(* replica reaching a version looks the same whether fan-out, a hint or     *)
(* anti-entropy delivered it - so the replay is a search, not a single      *)
(* path. Some branches dead-end: choosing anti-entropy for a leg of an open *)
(* fan-out leaves that fan-out unfinished and blocks the next event. Those  *)
(* dead ends are expected and are not conformance failures, which is why    *)
(* TLC runs this configuration with deadlock checking off.                  *)
(*                                                                         *)
(* The question is therefore whether *any* path explains the whole trace,   *)
(* and that is a reachability question. TraceIncomplete states the opposite *)
(* of what we want to be true, so TLC violating it is the witness: the      *)
(* counterexample it prints *is* the successful replay. Conformance fails   *)
(* when TLC finds no violation, having exhausted the search without ever    *)
(* explaining the final event.                                             *)
(*                                                                         *)
(* scripts/trace-conformance.sh interprets the result, because an exit code *)
(* that means the opposite of its usual thing is exactly the sort of detail *)
(* that rots into a check nobody notices is inverted.                       *)
(***************************************************************************)
TraceIncomplete ==
    ti <= Len(TraceEvents)

(* The recorded nodes must be the ones the configuration models, or the
   replay would be checking a different cluster than the one recorded. *)
ASSUME TraceNodes = Nodes

=============================================================================
